before_script:
    - apt-get update -qq && apt-get install -y -qq libsodium-dev
    - erl +V

stages:
    - build

test-18.3:
    image: ahfaeroey/otp:18.3
    stage: build
    script:
        - make

#test-19.0:
#    image: ahfaeroey/otp:19.0
#    stage: test
#    script:
#        - make check
